name: 'Linux x86-64'
on: push

jobs:
  linux-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y-%m-%d-%H;%M;%S")"
        shell: bash
      - name: ccache cache files
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: linux-x86-64-${{ runner.os }}-${{ steps.get-date.outputs.date }}
          restore-keys: |
              linux-x86-64-${{ runner.os }}-
      - name: Prepare dependencies
        shell: bash
        run: |
          mkdir -p /tmp/third-party && cd /tmp/third-party
          curl -LO https://data.romainthomas.fr/icdump/LLVM-14.0.6-Linux-slim.tar.gz
          curl -LO https://data.romainthomas.fr/icdump/LIEF-0.13.0-Linux-x86_64.tar.gz
      - name: Build Python 3.8 wheel
        shell: bash
        env:
          PYTHON_VERSION: 38
        run: |
          docker run --rm \
           -e CCACHE_COMPRESS=1 \
           -e CCACHE_MAXSIZE=10.0G \
           -e CCACHE_CPP2=1 \
           -e CCACHE_DIR=/ccache \
           -e PYTHON_VERSION=$PYTHON_VERSION \
           -e PYTHON_BINARY=/opt/python/cp38-cp38/bin/python \
           -v /tmp/third-party:/third-party \
           -v $GITHUB_WORKSPACE:/icdump \
           -v $HOME/.ccache:/ccache \
           rh0main/icdump_manylinux_2_28_x86_64 bash /icdump/scripts/docker/compile_icdump.sh
      - name: Build Python 3.9 wheel
        shell: bash
        env:
          PYTHON_VERSION: 39
        run: |
          docker run --rm \
           -e CCACHE_COMPRESS=1 \
           -e CCACHE_MAXSIZE=10.0G \
           -e CCACHE_CPP2=1 \
           -e CCACHE_DIR=/ccache \
           -e PYTHON_VERSION=$PYTHON_VERSION \
           -e PYTHON_BINARY=/opt/python/cp39-cp39/bin/python \
           -v /tmp/third-party:/third-party \
           -v $GITHUB_WORKSPACE:/icdump \
           -v $HOME/.ccache:/ccache \
           rh0main/icdump_manylinux_2_28_x86_64 bash /icdump/scripts/docker/compile_icdump.sh
      - name: Build Python 3.10 wheel
        shell: bash
        env:
          PYTHON_VERSION: 310
        run: |
          docker run --rm \
           -e CCACHE_COMPRESS=1 \
           -e CCACHE_MAXSIZE=10.0G \
           -e CCACHE_CPP2=1 \
           -e CCACHE_DIR=/ccache \
           -e PYTHON_VERSION=$PYTHON_VERSION \
           -e PYTHON_BINARY=/opt/python/cp310-cp310/bin/python \
           -v /tmp/third-party:/third-party \
           -v $GITHUB_WORKSPACE:/icdump \
           -v $HOME/.ccache:/ccache \
           rh0main/icdump_manylinux_2_28_x86_64 bash /icdump/scripts/docker/compile_icdump.sh
      - name: Build Python 3.11 wheel
        shell: bash
        env:
          PYTHON_VERSION: 311
        run: |
          docker run --rm \
           -e CCACHE_COMPRESS=1 \
           -e CCACHE_MAXSIZE=10.0G \
           -e CCACHE_CPP2=1 \
           -e CCACHE_DIR=/ccache \
           -e PYTHON_VERSION=$PYTHON_VERSION \
           -e PYTHON_BINARY=/opt/python/cp311-cp311/bin/python \
           -v /tmp/third-party:/third-party \
           -v $GITHUB_WORKSPACE:/icdump \
           -v $HOME/.ccache:/ccache \
           rh0main/icdump_manylinux_2_28_x86_64 bash /icdump/scripts/docker/compile_icdump.sh
